---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidytext)
library(janeaustenr)
```

```{r}
titles <- c("Pride and Prejudice", "Sense and Sensibility")

books <- list(prideprejudice, sensesensibility)

books <- map_chr(books, paste, collapse = " ")

```

```{r}
books_df <- tibble(
  title = titles,
  text = books
) %>%
  unnest_tokens(word, text)

```


## Most common words in Pride & Prejudice and Sense & Sensibilty


```{r}
books_count <- books_df %>%
  group_by(title) %>%
  count(word) %>%
  slice_max(n, n = 3)

books_count
```

## Most common words again but exclude stop words

```{r}
books_count_excluded_sw <- books_df %>%
  anti_join(stop_words) %>%
  group_by(title) %>%
  count(word) %>%
  slice_max(n, n = 3)

books_count_excluded_sw
```

## Most common sentiment words in Pride & Predjudice and Sense & Sensibility

```{r}
books_df %>%
  inner_join(get_sentiments("bing")) %>%
  group_by(title) %>%
  count(word) %>%
  slice_max(n, n = 5)
```



