---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(GGally)
library(ggfortify)
```


```{r}
diamonds <- read_csv("data/diamonds.csv")

summary(diamonds)
```

```{r}
diamonds %>%
  select(carat, x, y, z) %>%
  ggpairs(diamonds)
```

```{r}
diamonds_trimmed <- diamonds %>%
  select(-c(x:z))
```

```{r}
ggpairs(diamonds_trimmed)
```


```{r}
diamonds_trimmed %>%
  ggplot(aes(carat, price)) +
  geom_point() +
  geom_smooth(method = "lm", se = F)
```

```{r}
diamonds_trimmed %>%
  select(cut, clarity, color) %>%
  summarise_all(list(~n_distinct(.) -1))
```

```{r}
diamonds_trimmed %>%
  ggplot(aes(x = price, y = carat)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```
```{r}
model1 <- lm(price ~ carat, diamonds_trimmed)
summary(model1)
autoplot(model1)
```
```{r}
model2 <- lm(price ~ carat + clarity , diamonds_trimmed)
summary(model2)
autoplot(model2)
```



```{r}
diamonds_trimmed_dummy <- diamonds_trimmed %>%
  fastDummies::dummy_cols(select_columns = "clarity", remove_first_dummy = TRUE, remove_selected_columns = TRUE) %>%
  janitor::clean_names()
model3 <- lm(price ~ carat + clarity_if , diamonds_trimmed_dummy)
summary(model3)
autoplot(model3)
```

Not really sure if it should be `model2` or `model3` for the last question of the mvp