---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(GGally)
library(ggfortify)
library(modelr)
```

```{r}
kc_house <- read_csv("data/kc_house_data.csv")
```

# Tidying up data for regression 

```{r}
houses_tidy <- kc_house %>%
  rename(renovated = yr_renovated) %>%
  mutate(across(c("waterfront", "renovated"), as.logical),
        grade_high = ifelse(grade >= 11, 1, 0),
        grade_avg = ifelse(grade >= 4 & grade < 11, 1, 0)) %>%
  select(-c("date", "id", "sqft_living15", "sqft_lot15", "zipcode", "grade")) %>%
  fastDummies::dummy_cols(select_columns = "condition",
                          remove_first_dummy = TRUE,
                          remove_selected_columns = TRUE)
        
```

```{r}
glimpse(houses_tidy)
```

# Checked for aliased variables using the alias() function

```{r}
alias(lm(price ~ ., data = houses_tidy))

houses_tidy <- houses_tidy %>%
  select(-sqft_basement)
```

# Build regression model

```{r}
houses_tidy_numeric <- houses_tidy %>%
  select_if(is.numeric)

houses_tidy_nonnumeric <- houses_tidy %>%
  select_if(function(x) !is.numeric(x))

houses_tidy_nonnumeric$price <- houses_tidy$price

ggpairs(houses_tidy_numeric)
ggpairs(houses_tidy_nonnumeric)
```

```{r}
mod1 <- lm(price ~ sqft_living, data = houses_tidy_numeric)
summary(mod1)
autoplot(mod1)
```



```{r}
houses_remaining_resid <- houses_tidy_numeric %>%
  add_residuals(mod1) %>%
  select(-c("price", "sqft_living"))

houses_remaining_resid %>%
  ggpairs()
```



```{r}
mod2 <- lm(price ~ bathrooms, data = houses_tidy_numeric)

summary(mod2)
autoplot(mod2)
```

```{r}
mod3 <- lm(price ~ sqft_living + bathrooms, data = houses_tidy_numeric)

summary(mod3)
autoplot(mod3)
```

